# Generated by Django 5.2.13 on 2026-04-10 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='loan',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Hình ảnh'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Sẵn sàng cho mượn'),
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày mượn')),
                ('end_date', models.DateField(verbose_name='Ngày trả')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('returned', 'Đã trả')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người mượn')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Lượt mượn',
                'verbose_name_plural': 'Lượt mượn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='borrow_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='inventory.borrowrequest'),
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
