# Generated by Django 5.2.13 on 2026-04-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_conversation_loan_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Đã đăng lên trang chủ'),
        ),
    ]
